USE master;
GO

CREATE DATABASE NOTEMUSIC;
GO

IF EXISTS (SELECT * FROM sys.databases WHERE name = 'NOTEMUSIC')
    DROP DATABASE NOTEMUSIC;
GO

USE NOTEMUSIC;
GO

DROP TABLE TB_MUSICAS

CREATE TABLE TB_MUSICAS 
(
	ID				INT				IDENTITY,
    NOME_MUS		VARCHAR(255)	NOT NULL,
    ARTISTA			VARCHAR(255)	NOT NULL,
    ALBUM_MUS		VARCHAR(255)	NOT NULL,
	GENERO_MUS		VARCHAR(255)
);

INSERT INTO TB_MUSICAS (NOME_MUS, ARTISTA, ALBUM_MUS)
VALUES
	('IF YOURE TOO SHY (LET ME KNOW)', 'THE 1975', 'NOTES ON A CONDICIONAL FORM'),
	('TASTE', 'SABRINA CARPENTER', 'SHORT N SWEET'),
	('BACKSLIDE', 'TWENTY ONE PILOTS', 'CLANCY'),
	('360', 'CHARLI XCX', 'BRAT'),
	('OLHA BELA', 'LAGUM', 'DEPOIS DO FIM'),
	('MODO DE DIZER', 'JÃO', 'SUPERNOVA'),
	('BETTER THAN GOLD', 'NCT DREAM', 'GLITCH MODE'),
	('SUPERSONIC', 'FROMIS_9', 'SUPERSONIC'),
	('PINK PONY CLUB', 'CHAPPELL ROAN', 'THE RISE AND FALL OF A MIDWEST PRINCESS'),
	('NA NA NA (NA NA NA NA NA NA NA NA NA)', 'MY CHEMICAL ROMANCE', 'DANGER DAYS: THE TRUE LIVES OF THE FABULOUS KILLJOYS'),
	('OVERCOMPENSATE', 'TWENTY ONE PILOTS', 'CLANCY'),
	('NAVIGATING', 'TWENTY ONE PILOTS', 'CLANCY'),
	('NEXT SEMESTER', 'TWENTY ONE PILOTS', 'CLANCY'),
	('SNAP BACK', 'TWENTY ONE PILOTS', 'CLANCY'),
	('AT THE RISK OF FEELING DUMB', 'TWENTY ONE PILOTS', 'CLANCY'),
	('OLDIES STATION', 'TWENTY ONE PILOTS', 'CLANCY'),
	('THE CRAVING (JENNAS VERSION)', 'TWENTY ONE PILOTS', 'CLANCY'),
	('GOOD GRACES', 'SABRINA CARPENTER', 'SHORT N SWEET'),
	('SHARPEST TOOL', 'SABRINA CARPENTER', 'SHORT N SWEET'),
	('COINCIDENCE', 'SABRINCA CARPENTER', 'SHORT N SWEET')


SELECT * FROM TB_MUSICAS
ORDER BY ALBUM_MUS